In [1]:
import pandas as pd
df = pd.read_csv('top50contry.csv', encoding='latin-1')

In [2]:
df.shape

(1000, 17)

In [3]:
df.head()

,Unnamed: 0,title,artist,top genre,year,added,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop,country
0,1,Dance Monkey,Tones and I,australian pop,2019,1969-12-31,98.0,59.0,82.0,-6.0,15.0,51.0,209,69.0,9.0,100,world
1,2,ROXANNE,Arizona Zervas,pop rap,2019,1969-12-31,117.0,60.0,62.0,-6.0,46.0,46.0,164,5.0,15.0,99,world
2,3,Memories,Maroon 5,pop,2019,1969-12-31,91.0,32.0,76.0,-7.0,8.0,57.0,189,84.0,5.0,99,world
3,4,Circles,Post Malone,dfw rap,2019,1969-12-31,120.0,76.0,70.0,-3.0,9.0,55.0,215,19.0,4.0,99,world
4,5,All I Want for Christmas Is You,Mariah Carey,dance pop,1994,1969-12-31,150.0,63.0,34.0,-7.0,7.0,35.0,241,16.0,4.0,98,world

In [4]:
df.columns

Index(['Unnamed: 0', 'title', 'artist', 'top genre', 'year', 'added', 'bpm',
       'nrgy', 'dnce', 'dB', 'live', 'val', 'dur', 'acous', 'spch', 'pop',
       'country'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   title       1000 non-null   str
 2   artist      1000 non-null   str
 3   top genre   985 non-null    str
 4   year        1000 non-null   int64
 5   added       1000 non-null   str
 6   bpm         999 non-null    float64
 7   nrgy        999 non-null    float64
 8   dnce        999 non-null    float64
 9   dB          999 non-null    float64
 10  live        999 non-null    float64
 11  val         999 non-null    float64
 12  dur         1000 non-null   int64
 13  acous       999 non-null    float64
 14  spch        999 non-null    float64
 15  pop         1000 non-null   int64
 16  country     1000 non-null   str
dtypes: float64(8), int64(4), str(5)
memory usage: 132.9 KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1000.0,500.500000,288.819436,1.0,250.75,500.5,750.25,1000.0
year,1000.0,2010.025000,16.904264,1942.0,2011.00,2019.0,2019.00,2019.0
bpm,999.0,123.644645,31.005120,47.0,98.00,120.0,147.00,205.0
nrgy,999.0,61.650651,19.064732,10.0,49.00,65.0,76.00,98.0
dnce,999.0,64.282282,16.032857,16.0,53.00,67.0,76.00,95.0
dB,999.0,-6.807808,3.241313,-23.0,-8.00,-6.0,-5.00,0.0
live,999.0,20.003003,17.956443,2.0,9.00,12.0,25.00,98.0
val,999.0,59.732733,22.000356,5.0,42.00,61.0,77.00,98.0
dur,1000.0,206.074000,51.224198,85.0,172.00,201.0,231.00,464.0
acous,999.0,34.894895,28.778784,0.0,10.00,27.0,59.00,99.0
spch,999.0,8.703704,8.432230,2.0,4.00,5.0,9.00,56.0
pop,1000.0,81.443000,13.090229,0.0,75.00,85.0,90.00,100.0

In [24]:
df.describe(include= 'str').T

      count unique           top  freq
title  1000    527  Dance Monkey    17
added  1000      1    1969-12-31  1000

In [8]:
df.nunique()

Unnamed: 0    1000
title          527
artist         358
top genre      112
year            45
added            1
bpm            110
nrgy            85
dnce            68
dB              21
live            70
val             92
dur            184
acous           96
spch            45
pop             60
country         20
dtype: int64

In [9]:
df['country'].unique()

<StringArray>
[    'world',    'africa', 'argentina', 'australia',   'belgium',   'bolivia',
    'brazil',    'canada',   'germany',  'colombia',     'chile',     'spain',
       'usa',    'france',     'india', 'indonesia',    'israel',     'italy',
     'japan',   'malasya']
Length: 20, dtype: str

In [10]:
df['country'].value_counts()

country
world        50
africa       50
argentina    50
australia    50
belgium      50
bolivia      50
brazil       50
canada       50
germany      50
colombia     50
chile        50
spain        50
usa          50
france       50
india        50
indonesia    50
israel       50
italy        50
japan        50
malasya      50
Name: count, dtype: int64

In [11]:
print(df['top genre'].unique())

<StringArray>
[           'australian pop',                   'pop rap',
                       'pop',                   'dfw rap',
                 'dance pop',                'electropop',
           'alternative r&b',                     'latin',
 'canadian contemporary r&b',           'adult standards',
 ...
       'classic israeli pop',             'trap italiana',
           'italian hip hop',               'italian pop',
                'anime rock',                     'j-pop',
                'j-acoustic',          'kodomo no ongaku',
           'malaysian indie',         'malaysian hip hop']
Length: 113, dtype: str

In [12]:
df['artist'].unique()

<StringArray>
[        'Tones and I',      'Arizona Zervas',            'Maroon 5',
         'Post Malone',        'Mariah Carey',       'Billie Eilish',
       'Trevor Daniel', 'The Black Eyed Peas',            'Dua Lipa',
             'KAROL G',
 ...
         'Sakanaction',             'GReeeeN',            'Superfly',
              'Foorin',           'MONGOL800',         'Don Toliver',
        'Taylor Swift',               'Bazzi',            'K-Clique',
             'MeerFly']
Length: 358, dtype: str

In [13]:
df = df.drop(columns=["Unnamed: 0"])
df.rename(columns= {'top genre':'genre'}, inplace= True)

In [14]:
def generate_id_and_dim_table(name_column,DataFrame):
    lst_column = list(DataFrame[name_column].unique())
    new_df = pd.DataFrame(lst_column, columns=[name_column])
    new_id_column = DataFrame[name_column].map({name: i+1 for i,name in enumerate(lst_column)})
    return new_id_column, new_df

In [15]:
df['artist'], df_artist = generate_id_and_dim_table('artist',df)
df['genre'], df_genre = generate_id_and_dim_table('genre',df)
df['country'], df_country = generate_id_and_dim_table('country',df)

In [16]:
df.rename(columns= {'artist':'artist_id'}, inplace= True)
df.rename(columns= {'genre':'genre_id'}, inplace= True)
df.rename(columns= {'country':'country_id'}, inplace= True)

In [17]:
# pip install criptography

In [18]:
from sqlalchemy import create_engine, text 
import config

In [19]:
engine = create_engine(config.DATABASE_URL)

In [20]:
# 2. Lectura del archivo con el schema
with open('schema_Spotify_proyect.sql', 'r', encoding='utf-8') as file:
    sql_schema = file.read()

# 3. Ejecución del schema en la base de datos
try:
    with engine.connect() as connection:
        # Dividimos por ";" por si hay varias instrucciones y las ejecutamos
        # Nota: Algunos drivers permiten ejecutar todo el bloque de golpe
        for statement in sql_schema.split(';'):
            if statement.strip():
                connection.execute(text(statement))
        connection.commit()
    print("Schema cargado correctamente.")
except Exception as e:
    print(f"Error al cargar el schema: {e}")

Schema cargado correctamente.

In [21]:
# 1. Crear un motor que apunte DIRECTAMENTE a la base de datos
# Asegúrate de que la URL incluya el nombre de la DB al final
engine_db = create_engine(config.DATABASE_URL + "Spotify_proyect")

# 2. Volcado de las tablas usando el nuevo motor (engine_db)
try:
    df_country.to_sql('country', con=engine_db, if_exists='append', index=False)
    df_artist.to_sql('artist', con=engine_db, if_exists='append', index=False)
    df_genre.to_sql('genre', con=engine_db, if_exists='append', index=False)
    df.to_sql('top50_country', con=engine_db, if_exists='append', index=False)
    print("¡Datos cargados exitosamente en todas las tablas!")
except Exception as e:
    print(f"Error al cargar los datos: {e}")

¡Datos cargados exitosamente en todas las tablas!